version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ragbot
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./text_files:/app/text_files
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ragbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 